name: Node.js CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
      - name: Install dependencies
        run: pnpm install
      - name: Build and Export
        run: |
          pnpm build
          pnpm export
          touch out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: out
          clean: true
